version: 2
jobs:
  build:
    docker:
      - image: bentonam/couchbase-docker:enterprise-5.1.0
        ports:
          - "8091-8094:8091-8094"
          - "9110:9110"
          - "11207-11212:11207-11212"
          - "18091-18094:18091-18094"
        environment:
          COUCHBASE_HOST: localhost
          COUCHBASE_BUCKET: example
          COUCHBASE_PORT: 8091
          CLUSTER_USERNAME: Administrator
          CLUSTER_PASSWORD: password
          BUCKET: example
          RBAC_USERNAME: example
          RBAC_PASSWORD: 123456
          RBAC_ROLES: bucket_full_access[example]
    working_directory: ~/docker-cean
    environment:
      COUCHBASE_HOST: localhost
      COUCHBASE_BUCKET: example
      COUCHBASE_PORT: 8091
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: password
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "node/package.json" }}
            - dependency-cache- # used if checksum fails
      - run:
          name: Artifacts directory creation
          command: mkdir -p ~/docker-cean/artifacts && mkdir -p ~/docker-cean/test-results
      - run:
          name: "Test couchbase"
          command: |
            sleep 20
            curl -X GET -u $CLUSTER_USERNAME:$CLUSTER_PASSWORD --retry 10 --retry-delay 10 -v http://$COUCHBASE_HOST:$COUCHBASE_PORT/pools/$COUCHBASE_BUCKET/buckets -C -
      - save_cache:
          key: dependency-cache-{{ checksum "node/package.json" }}
          paths:
            - node_modules
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: ~/docker-cean/artifacts
          destination: artifacts
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results
          destination: test-results/junit
