version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce
    working_directory: ~/docker-cean
    environment:
      IMAGE_NAME: couchbase
      DOCKER_REPO: bentonam
      COUCHBASE_HOST: localhost
      COUCHBASE_BUCKET: example
      COUCHBASE_PORT: 8091
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: password
      BUCKET: example
      RBAC_USERNAME: example
      RBAC_PASSWORD: 123456
      RBAC_ROLES: bucket_full_access[example]
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "node/package.json" }}
            - dependency-cache- # used if checksum fails
      - run:
          name: Artifacts directory creation
          command: mkdir -p ~/docker-cean/artifacts && mkdir -p ~/docker-cean/test-results
      - run:
          name: "Install tools"
          command: |
            apk update
            apk add --no-cache wget
            apk add --no-cache curl
      - run:
          name: "Starting docker"
          command: |
            docker info >/dev/null 2>&1 || service docker start
            docker version
      - run:
          name: "Docker info"
          command: |
            docker info
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            echo Couchbase host: $DOCKERHOST
      - run:
          name: "Starting couchbase"
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_BUILD_NUM .circleci/
            docker run -d --name couchtest -p 8091-8094:8091-8094 -p 9110:9110 -p 11207-11211:11207-11211 -p 18091-18094:18091-18094 -t $IMAGE_NAME:$CIRCLE_BUILD_NUM
            sleep 20
            # A running cluster will respond with cluster status.
            docker logs --tail=200 couchtest > ~/docker-cean/artifacts/couchbase.log
      - run:
          name: "Test couchbase"
          command: |
            sleep 20
            curl -X GET -u $CLUSTER_USERNAME:$CLUSTER_PASSWORD --retry 10 --retry-delay 10 -v http://$COUCHBASE_HOST:$COUCHBASE_PORT/pools/$COUCHBASE_BUCKET/buckets -C -
      - save_cache:
          key: dependency-cache-{{ checksum "node/package.json" }}
          paths:
            - node_modules
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: ~/docker-cean/artifacts
          destination: artifacts
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results
          destination: test-results/junit
